data:
  flickr30k_path: "data/flickr30k"
  max_samples: 20000
training:
  batch_size: 16
  learning_rate: 2e-5
  epochs: 50
  output_dir: "checkpoints"
  contrastive_weight: 0.5
  generation_weight: 0.5
model:
  llm: "Qwen/Qwen2-0.5B"
  vision: "openai/clip-vit-base-patch32"
  lora_rank: 16
dataloader:
  num_workers: 4