data:
  flickr8k_path: "data/flickr8k"
  cifar10_path: "data/cifar10"
  max_samples: 20000
training:
  batch_size: 16
  learning_rate: 2e-5
  epochs: 5
  output_dir: "checkpoints"
  contrastive_weight: 0.5
  generation_weight: 0.5
model:
  llm: "Qwen/Qwen2-0.5B"
  vision: "openai/clip-vit-base-patch32"
  lora_rank: 16